"use client";
import { FormEvent, useEffect, useState } from "react";
type Exercise={id:string;name:string;category:string[];instructions:string|null;mediaUrl:string|null};
const categories=["전체","가슴","등","어깨","팔","하체","코어","유산소","기타"];
export default function ExerciseBook(){
 const [trainerId,setTrainerId]=useState(""),[category,setCategory]=useState("전체"),[exercises,setExercises]=useState<Exercise[]>([]),[selected,setSelected]=useState<Exercise|null>(null),[editing,setEditing]=useState<Exercise|null>(null),[creating,setCreating]=useState(false),[media,setMedia]=useState(""),[selectedCategories,setSelectedCategories]=useState<string[]>([]);
 const load=async(c=category)=>{const r=await fetch(`/api/exercises?category=${encodeURIComponent(c)}`);setExercises(r.ok?await r.json():[])};
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("trainerId")||localStorage.getItem("fitlog-trainer-id")||"";setTrainerId(id);void load("전체")},[]);
 useEffect(()=>{document.querySelector(".trainer-bottom-nav")?.remove();const nav=document.createElement("nav");nav.className="trainer-bottom-nav";[["회원 관리",`/members?trainerId=${trainerId}&trainer=1`],["운동 일지",`/trainer/logs?trainerId=${trainerId}`],["운동 책자","#"],["마이페이지",`/trainer/my?trainerId=${trainerId}`]].forEach(([label,href],i)=>{const a=document.createElement("a");a.textContent=label;a.href=href;if(i===2)a.className="selected";nav.append(a)});document.body.append(nav);return()=>nav.remove()},[trainerId]);
 const choose=(c:string)=>{setCategory(c);void load(c)};
 const fileToData=(file:File)=>{const reader=new FileReader();reader.onload=()=>setMedia(String(reader.result||""));reader.readAsDataURL(file)};
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const payload={name:f.get("name"),categories:selectedCategories,instructions:f.get("instructions"),mediaUrl:media||editing?.mediaUrl||""};const r=await fetch(editing?`/api/exercises/${editing.id}`:"/api/exercises",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(r.ok){setCreating(false);setEditing(null);setSelected(null);setMedia("");setSelectedCategories([]);await load()}}
 async function remove(){if(!editing)return;const r=await fetch(`/api/exercises/${editing.id}`,{method:"DELETE"});if(r.ok){setEditing(null);setSelected(null);await load()}}
 const form=creating||editing;
 return <main className="page-shell"><h1>운동 책자</h1><section className="card"><div className="category-tabs">{categories.map(c=><button key={c} className={category===c?"selected":""} onClick={()=>choose(c)}>{c}</button>)}</div><ul className="member-list">{exercises.length?exercises.map(x=><li key={x.id}><button className="trainer-name" onClick={()=>setSelected(x)}><strong>{x.name}</strong><span>{x.category.join(" · ")}</span></button></li>):<p className="hint">등록된 운동이 없습니다.</p>}</ul></section><button className="floating-add" onClick={()=>{setCreating(true);setEditing(null);setMedia("");setSelectedCategories([])}}>＋</button>{selected&&!form&&<div className="modal-backdrop"><section className="modal-card"><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div className="list-title"><h2>{selected.name}</h2><button className="gear-button" onClick={()=>{setEditing(selected);setMedia("");setSelectedCategories(selected.category)}}>⚙</button></div><p className="hint">카테고리: {selected.category.join(" · ")}</p><p>{selected.instructions||"등록된 운동방법이 없습니다."}</p>{selected.mediaUrl&&(selected.mediaUrl.startsWith("data:video")?<video controls src={selected.mediaUrl}/>:<img className="exercise-media" src={selected.mediaUrl} alt={`${selected.name} 첨부`} />)}</section></div>}{form&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><button type="button" className="modal-close" onClick={()=>{setCreating(false);setEditing(null);setMedia("");setSelectedCategories([])}}>×</button><h2>{editing?"운동 수정":"운동 등록"}</h2><label>카테고리<div className="category-checks">{categories.slice(1).map(c=><label key={c}><input type="checkbox" checked={selectedCategories.includes(c)} onChange={()=>setSelectedCategories(selectedCategories.includes(c)?selectedCategories.filter(x=>x!==c):[...selectedCategories,c])}/>{c}</label>)}</div></label><label className="exercise-name-field">운동명<input name="name" required defaultValue={editing?.name}/></label><label>운동방법<textarea name="instructions" defaultValue={editing?.instructions||""}/></label><label>사진/영상 첨부<input type="file" accept="image/*,video/*" onChange={e=>{const file=e.target.files?.[0];if(file)fileToData(file)}}/></label><div className="modal-actions"><button>{editing?"수정":"등록"}</button>{editing&&<button type="button" className="danger" onClick={()=>void remove()}>삭제</button>}</div></form></div>}</main>;
}
