"use client";
import { useRef, useState } from "react";
import { parseWorkoutTranscript, type WorkoutParseResult } from "@/lib/workout-parser";
type RecognitionEvent = Event & { results: SpeechRecognitionResultList };
type Recognition = { lang: string; continuous: boolean; interimResults: boolean; onresult: ((event: RecognitionEvent) => void) | null; onerror: ((event: Event & { error: string }) => void) | null; onend: (() => void) | null; start(): void; stop(): void };
type RecognitionConstructor = new () => Recognition;
declare global { interface Window { SpeechRecognition?: RecognitionConstructor; webkitSpeechRecognition?: RecognitionConstructor } }
const empty: WorkoutParseResult = { exercises: [], uncertainFields: [] };
const t = { unsupported: "\uC774 \uBE0C\uB77C\uC6B0\uC800\uB294 \uC74C\uC131 \uC778\uC2DD\uC744 \uC9C0\uC6D0\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4. Chrome\uC744 \uC0AC\uC6A9\uD558\uAC70\uB098 \uC6D0\uBB38\uC744 \uC9C1\uC811 \uC785\uB825\uD558\uC138\uC694.", error: "\uC74C\uC131 \uC778\uC2DD \uC624\uB958", listening: "\uB4E3\uACE0 \uC788\uC2B5\uB2C8\uB2E4. \uC644\uB8CC\uB418\uBA74 \uB2E4\uC2DC \uB20C\uB7EC \uC885\uB8CC\uD558\uC138\uC694.", missing: "\uD68C\uC6D0 ID\uB97C \uC785\uB825\uD558\uACE0 \uC6B4\uB3D9 \uB370\uC774\uD130\uB97C \uBD84\uC11D\uD574 \uC8FC\uC138\uC694.", saving: "\uC800\uC7A5 \uC911...", saved: "\uC6B4\uB3D9\uC77C\uC9C0\uB97C \uC800\uC7A5\uD588\uC2B5\uB2C8\uB2E4.", failed: "\uC800\uC7A5\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.", stop: "\uB179\uC74C \uC885\uB8CC", start: "\uC74C\uC131\uC73C\uB85C \uAE30\uB85D", hint: "\uD55C\uAD6D\uC5B4\uB85C \uC790\uC5F0\uC2A4\uB7FD\uAC8C \uB9D0\uD558\uC138\uC694. \uC800\uC7A5 \uC804 \uBAA8\uB4E0 \uAC12\uC744 \uD655\uC778\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.", transcript: "\uC74C\uC131 \uC6D0\uBB38", placeholder: "\uB9D0\uD55C \uB0B4\uC6A9\uC774 \uC5EC\uAE30\uC5D0 \uD45C\uC2DC\uB429\uB2C8\uB2E4.", analyze: "\uC6B4\uB3D9 \uB370\uC774\uD130 \uBD84\uC11D", member: "\uD68C\uC6D0 ID", memberPlaceholder: "\uD68C\uC6D0 ID\uB97C \uC785\uB825\uD558\uC138\uC694.", review: "\uD655\uC778 \uBC0F \uC218\uC815", set: "\uC138\uD2B8", weight: "\uC911\uB7C9 (kg)", reps: "\uBC18\uBCF5", needed: "\uD655\uC778\uC774 \uD544\uC694\uD55C \uD56D\uBAA9", save: "\uD655\uC778 \uD6C4 \uC800\uC7A5" };
export function VoiceWorkoutRecorder() {
  const recorder = useRef<Recognition | null>(null); const [recording, setRecording] = useState(false); const [transcript, setTranscript] = useState(""); const [memberId, setMemberId] = useState(""); const [parsed, setParsed] = useState<WorkoutParseResult>(empty); const [message, setMessage] = useState("");
  const record = () => { if (recording) { recorder.current?.stop(); return; } const Constructor = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Constructor) { setMessage(t.unsupported); return; } const instance = new Constructor(); instance.lang = "ko-KR"; instance.continuous = true; instance.interimResults = true; instance.onresult = (event) => { let text = ""; for (let i = 0; i < event.results.length; i += 1) text += event.results[i][0].transcript; setTranscript(text.trim()); }; instance.onerror = (event) => { setMessage(`${t.error}: ${event.error}`); setRecording(false); }; instance.onend = () => setRecording(false); recorder.current = instance; instance.start(); setRecording(true); setMessage(t.listening); };
  const updateSet = (exerciseIndex: number, setIndex: number, field: "weight" | "repetitions", value: string) => setParsed((current) => ({ ...current, exercises: current.exercises.map((exercise, ei) => ei !== exerciseIndex ? exercise : { ...exercise, sets: exercise.sets.map((set, si) => si !== setIndex ? set : { ...set, [field]: value === "" ? null : Number(value) }) }) }));
  const save = async () => { if (!memberId || parsed.exercises.length === 0) { setMessage(t.missing); return; } setMessage(t.saving); const response = await fetch("/api/workout-logs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ memberId, workoutDate: new Date(), transcript, exercises: parsed.exercises }) }); const body = await response.json(); setMessage(response.ok ? t.saved : body.error ?? t.failed); };
  return <><section className="card"><button className={`record-action ${recording ? "is-recording" : ""}`} onClick={record} type="button">{recording ? t.stop : t.start}</button><p className="hint">{t.hint}</p>{message && <p className="status">{message}</p>}<label htmlFor="transcript">{t.transcript}</label><textarea id="transcript" value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder={t.placeholder} /><button className="save" type="button" onClick={() => setParsed(parseWorkoutTranscript(transcript))}>{t.analyze}</button></section>{parsed.exercises.length > 0 && <section className="card"><label htmlFor="member-id">{t.member}</label><input id="member-id" value={memberId} onChange={(event) => setMemberId(event.target.value)} placeholder={t.memberPlaceholder} /><h2>{t.review}</h2>{parsed.exercises.map((exercise, exerciseIndex) => <div className="exercise" key={`${exercise.name}-${exerciseIndex}`}><h3>{exercise.name}</h3><table><thead><tr><th>{t.set}</th><th>{t.weight}</th><th>{t.reps}</th></tr></thead><tbody>{exercise.sets.map((set, setIndex) => <tr key={set.setNumber}><td>{set.setNumber}</td><td><input type="number" min="0" value={set.weight ?? ""} onChange={(event) => updateSet(exerciseIndex, setIndex, "weight", event.target.value)} /></td><td><input type="number" min="0" value={set.repetitions ?? ""} onChange={(event) => updateSet(exerciseIndex, setIndex, "repetitions", event.target.value)} /></td></tr>)}</tbody></table></div>)}{parsed.uncertainFields.length > 0 && <p className="uncertain">{t.needed}: {parsed.uncertainFields.join(" ")}</p>}<button className="save" type="button" onClick={save}>{t.save}</button></section>}</>;
}
